### PR TITLE
Remove 2 commas

### PR DESCRIPTION
**Pull request by beepy**
Corrections made:
* remove comma "I heard them, say" per https://hdl.handle.net/2027/mdp.39015017962039?urlappend=%3Bseq=109
* remove comma "experience, has taught me" per https://hdl.handle.net/2027/mdp.39015017962039?urlappend=%3Bseq=149

### CODE REVIEW

**Comment by acabal** [comment]
I can't rebase this due to merge conflicts. Can you resolve the conflicts first? Did you accidentally include a previously commited typo fix in this pull request group?

**Comment by beepy** [comment]
Looks like I did include a previous fix, sorry. I merged `standardebooks:master` into this branch `beepy:patch-3` and pushed. There were no conflicts. Let me know if that works.

**Comment by acabal** [comment]
Still can't merge, it looks like there are just more commits in the pull request though. Maybe just clone fresh and make the change there in a new pull request.

**Comment by beepy** [comment]
Weird. Github stated there were no merge conflicts. I created a new branch with the two tiny fixes based off of freshly pulled `standardebooks:master` branch and made a new PR for that.

**Pull request closed without merging**
